/** Ready-driver shortlist from the original Tunga Taxi seed (identity only). */
export const DEFAULT_CANDIDATES = [
  { name: "TUYISENGE Gisele", phone: "786943123", gender: "female", district: "Nyarugenge", notes: "Preferred EV: NETA U 2023" },
  { name: "CYUBAHIRO Charite", phone: "788660491", gender: "male", district: "Kicukiro", notes: "Preferred EV: NETA U 2023" },
  { name: "EMMANUEL UWIZEYIMANA", phone: "787613076", gender: "male", district: "Gasabo", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "BUSHAIJA Blaise", phone: "788611098", gender: "male", district: "Nyarugenge", notes: "Preferred EV: BYD Yuan Plus 2023" },
  { name: "HAFASHIMANA Emmanuel", phone: "789752852", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Up 2024" },
  { name: "NDAYAMBAJE VEDASTE", phone: "788592350", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Plus 2025" },
  { name: "NIYONZIMA ERIC", phone: "789526485", gender: "male", district: "Nyarugenge", notes: "Preferred EV: NETA U PRO 2022" },
  { name: "MUGABO RASHID", phone: "788506578", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Plus 2025" },
  { name: "HABIMANA Jean Pierre", phone: "788359703", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "HABANIMFURA Celestin", phone: "788852087", gender: "male", district: "Nyarugenge", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "TURINZWENIMANA Bosco", phone: "781720701", gender: "male", district: "Kicukiro", notes: "Preferred EV: NETA U 2022" },
  { name: "UWIMANA Fred", phone: "788741210", gender: "male", district: "Gasabo", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "MUSABYIMANA John", phone: "788235722", gender: "male", district: "Nyarugenge", notes: "Preferred EV: NETA U 2022" },
  { name: "KARENZI Noel", phone: "788226247", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Up 2025 Basic" },
  { name: "NIZEYIMANA Janvier", phone: "787056547", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "NSIGAYEHE Gilbert", phone: "783670326", gender: "male", district: "Nyarugenge", notes: "Preferred EV: BYD Yuan Plus 2024" },
  { name: "MIZERO Protais", phone: "782722250", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Plus 2025" },
  { name: "NZEYIMANA Emmanuel", phone: "783308924", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "NKESHIMANA Marc", phone: "783664264", gender: "male", district: "Nyarugenge", notes: "Preferred EV: AION V Plus 2023" },
  { name: "HAKIZIMANA ALEX", phone: "780759619", gender: "male", district: "Kicukiro", notes: "Preferred EV: NETA U PRO 2022" },
  { name: "Munezero Alphonse", phone: "788445560", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Plus 2023" },
  { name: "NIYOYITA Jean Paul", phone: "788781763", gender: "male", district: "Nyarugenge", notes: "Preferred EV: BYD Song Plus" },
  { name: "SHYAKA Aimable", phone: "788536423", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "MPORAYONZI Vedaste", phone: "789921038", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "HAHAGAZINTWARI Eugene", phone: "788775059", gender: "male", district: "Nyarugenge", notes: "Preferred EV: AION V Plus 2023" },
  { name: "NDAGIJIMANA Innocent", phone: "788252428", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Plus 2024" },
  { name: "MURENZI Ildephonse", phone: "785201233", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Song Plus" },
  { name: "Ndayisenga Dominique", phone: "790550428", gender: "male", district: "Nyarugenge", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "RUGABA Henry Mark", phone: "788776045", gender: "male", district: "Kicukiro", notes: "Preferred EV: NETA U Pro 2023" },
  { name: "AHISHAKIYE Amur", phone: "788770876", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Plus 2024" },
  { name: "NYINAWUMUNTU ROSEMARY", phone: "788597303", gender: "female", district: "Nyarugenge", notes: "Preferred EV: BYD Yuan Up 2024" },
  { name: "GASORE Egide", phone: "785086198", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Up 2024" },
  { name: "NIZEYIMANA ABDUL KARIM", phone: "785762697", gender: "male", district: "Gasabo", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "TUYISENGE JEAN CLAUDE 2", phone: "790363974", gender: "male", district: "Nyarugenge", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "NKIKABAHIZI Joseph", phone: "788825856", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Up 2024" },
  { name: "UWAMARAYIKA VENUSTE", phone: "788211837", gender: "male", district: "Gasabo", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "KABUKIRE Eric", phone: "784945500", gender: "male", district: "Nyarugenge", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "KABUKIRE Aime", phone: "788864119", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "TUYISENGE JEAN CLAUDE", phone: "786661346", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Up 2025 Basic" },
  { name: "KASIRE Gratien", phone: "784417321", gender: "male", district: "Nyarugenge", notes: "Preferred EV: BYD Yuan Plus 2023" },
  { name: "NGIRINSHUTI Damascene", phone: "788372952", gender: "male", district: "Kicukiro", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "NDAYISENGA Emmanuel", phone: "733800284", gender: "male", district: "Gasabo", notes: "Preferred EV: Wuling EV 730" },
  { name: "RUTAYISIRE Bosco", phone: "785040266", gender: "male", district: "Nyarugenge", notes: "Preferred EV: BYD Yuan Up 2025" },
  { name: "ITEGEKWANANDE PIERRE", phone: "788610839", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Up 2024" },
  { name: "ICYOYISHAKIYE Dieudonne", phone: "788491388", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD E2 2023" },
  { name: "IRAKOZE Jean Viateur", phone: "785312245", gender: "male", district: "Nyarugenge", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "MUNYANEZA Celestin", phone: "788871413", gender: "male", district: "Kicukiro", notes: "Preferred EV: BYD Yuan Up 2024" },
  { name: "TUYIRINGIRE Jean Paul", phone: "788203558", gender: "male", district: "Gasabo", notes: "Preferred EV: Dongfeng E70 2023" },
  { name: "SHEBA KAGABO", phone: "788897577", gender: "male", district: "Nyarugenge", notes: "Preferred EV: Dongfeng Venucia Sedan 2023" },
  { name: "MUVUNYI Johnson", phone: "788816959", gender: "male", district: "Kicukiro", notes: "Preferred EV: Neta U Pro 2023" },
  { name: "NGOGA ABDOUL", phone: "788633531", gender: "male", district: "Gasabo", notes: "Preferred EV: BYD Yuan Up 2025" },
];
